base:
  project: body_fat_prediction_project
  random_state: 42
  target_col: BF

data_source:
  s3_source: data_given/fatdat.txt # s3_source just to replicate the data is coming from a remote data

load_data:
  raw_dataset_csv: data/raw/fatdat.csv

split_data:
  train_path: data/processed/train_fatdat.csv
  test_path: data/processed/test_fatdat.csv
  test_size: 0.2

model_dir: saved_models

model: random_forest.joblib

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: Body Fat Prediction
  run_name: mlops
  registered_model_name: Body Fat
  remote_server_uri: http://0.0.0.0:1234


  